"""Static API/navigation generation, link checks and reproducible documentation."""

import argparse
import ast
import html
import os
import re
import subprocess
import sys
from pathlib import Path
from urllib.parse import unquote

from markdown import Markdown
from markdown.extensions.toc import slugify_unicode

ROOT = Path(__file__).resolve().parents[1]
NOTICE = "<!-- Generated by tools.docs; do not edit. -->\n\n"


def module_name(path, source):
    parts = list(path.relative_to(source.parent).with_suffix("").parts)
    if parts[-1] == "__init__":
        parts.pop()
    return ".".join(parts)


def imports(tree, module, package=False):
    names = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            names.update(alias.name for alias in node.names)
        elif isinstance(node, ast.ImportFrom):
            prefix = module.split(".") if package else module.split(".")[:-1]
            base = prefix[: len(prefix) - node.level + 1] if node.level else []
            target = ".".join([*base, *([node.module] if node.module else [])])
            names.add(target)
            names.update(target + "." + alias.name for alias in node.names)
    return names


def definitions(root=ROOT):
    source = root / "src/opendoc"
    modules = {
        module_name(path, source): (path, ast.parse(path.read_text(encoding="utf-8-sig")))
        for path in sorted(source.rglob("*.py"))
    }
    if not modules:
        raise ValueError("No library modules found")
    return modules


def source_link(root, path, line=None):
    relative = path.relative_to(root).as_posix()
    return f"[{relative}](../../{relative}" + (f"#L{line}" if line else "") + ")"


def generated(root=ROOT):
    modules = definitions(root)
    code = [
        "# Навигатор по коду",
        "",
        "Статический AST: определения, внутренние импорты и прямые импорты тестов. Ссылки на тесты не означают покрытие.",
        "",
    ]
    tests = {
        path: imports(ast.parse(path.read_text(encoding="utf-8")), "tests." + path.stem)
        for path in sorted((root / "tests").glob("test_*.py"))
    }
    for module, (path, tree) in modules.items():
        code += [f'<a id="{module.replace(".", "-")}"></a>', f"## {module}", "", source_link(root, path), ""]
        doc = ast.get_docstring(tree)
        if doc:
            code += [html.escape(doc.splitlines()[0]), ""]
        for node in tree.body:
            if isinstance(node, (ast.ClassDef, ast.FunctionDef, ast.AsyncFunctionDef)) and not node.name.startswith("_"):
                code += [f"- `{node.name}` — " + source_link(root, path, node.lineno)]
        dependencies = sorted(
            name for name in imports(tree, module, path.name == "__init__.py") if name in modules and name != module
        )
        code += [
            "",
            "Импорты: "
            + (", ".join(f"[{name}](#{name.replace('.', '-')})" for name in dependencies) or "нет внутренних импортов")
            + ".",
            "",
        ]
        direct_tests = [source_link(root, test) for test, names in tests.items() if module in names]
        code += ["Прямые импорты в тестах: " + (", ".join(direct_tests) or "не найдены") + ".", ""]
    api = [
        "# Справочник API",
        "",
        "Корневые экспорты `opendoc` извлечены из явных импортов. Ссылки ведут к объявлениям и точным строкам исходников.",
        "",
        "| Имя | Модуль | Объявление |",
        "|---|---|---|",
    ]
    for node in modules["opendoc"][1].body:
        if not isinstance(node, ast.ImportFrom) or node.level != 1 or not node.module:
            continue
        module = "opendoc." + node.module
        path, tree = modules[module]
        for alias in node.names:
            public = alias.asname or alias.name
            declared = next((item for item in tree.body if getattr(item, "name", None) == alias.name), None)
            api.append(f"| `{public}` | `{module}` | {source_link(root, path, declared.lineno if declared else None)} |")
    api += ["", "## Объявления", ""]
    for node in modules["opendoc"][1].body:
        if not isinstance(node, ast.ImportFrom) or node.level != 1 or not node.module:
            continue
        path, tree = modules["opendoc." + node.module]
        for alias in node.names:
            declared = next((item for item in tree.body if getattr(item, "name", None) == alias.name), None)
            if declared is None:
                continue
            api += [f"### {alias.asname or alias.name}", "", source_link(root, path, declared.lineno), ""]
            if isinstance(declared, (ast.FunctionDef, ast.AsyncFunctionDef)):
                api += ["```python", f"{declared.name}({ast.unparse(declared.args)})", "```", ""]
            doc = ast.get_docstring(declared)
            if doc:
                api += [html.escape(doc), ""]
    guide = ["# Руководство — навигация", ""]
    for path in sorted((root / "docs/guide").glob("*.md")):
        body = re.sub(r"^```.*?^```[^\n]*", "", path.read_text(encoding="utf-8"), flags=re.MULTILINE | re.DOTALL)
        for title in re.findall(r"^## (.+)$", body, re.MULTILINE):
            guide.append(f"- [{title}](../guide/{path.name}#{slugify_unicode(title, '-')})")
    return {
        "docs/reference/code.md": NOTICE + "\n".join(code) + "\n",
        "docs/reference/api.md": NOTICE + "\n".join(api) + "\n",
        "docs/reference/user-guide.md": NOTICE + "\n".join(guide) + "\n",
    }


def sync(check=False, root=ROOT):
    for name, content in generated(root).items():
        path = root / name
        if not path.exists() or path.read_text(encoding="utf-8") != content:
            if check:
                raise ValueError(f"Stale generated page: {name}; run tools.docs generate")
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")


def contents(root=ROOT):
    pages = {
        path.relative_to(root).as_posix(): path.read_text(encoding="utf-8")
        for path in [*root.glob("*.md"), *(root / "docs").rglob("*.md")]
    }
    pages.update(generated(root))
    return pages


def anchors(content):
    rendered = Markdown(
        extensions=["toc", "fenced_code", "tables"], extension_configs={"toc": {"slugify": slugify_unicode}}
    ).convert(content)
    return set(re.findall(r'id="([^"]+)"', rendered))


def rewrite_links(content, name, pages, assets, root=ROOT):
    def replace(match):
        url = unquote(match[1])
        if re.match(r"[a-zA-Z]+://|mailto:", url):
            return match[0]
        location, _, fragment = url.partition("#")
        target = ((root / name).parent / location).resolve() if location else (root / name).resolve()
        if not target.is_relative_to(root.resolve()):
            raise ValueError(f"{name}: invalid local link {url}")
        relative = target.relative_to(root).as_posix()
        if relative not in pages and not target.is_file():
            raise ValueError(f"{name}: invalid local link {url}")
        if relative in pages:
            if fragment and fragment not in anchors(pages[relative]):
                raise ValueError(f"{name}: missing anchor {url}")
            destination = relative
        else:
            text = target.read_text(encoding="utf-8-sig")
            if fragment and (not re.fullmatch(r"L\d+", fragment) or int(fragment[1:]) > len(text.splitlines())):
                raise ValueError(f"{name}: invalid source anchor {url}")
            destination = "files/" + relative + ".html"
            lines = "\n".join(
                f'<span id="L{index}"><a href="#L{index}">{index:4}</a> {html.escape(line)}</span>'
                for index, line in enumerate(text.splitlines(), 1)
            )
            assets[destination] = (
                f'<!doctype html><html lang="ru"><meta charset="utf-8"><title>{html.escape(relative)}</title>'
                "<style>body{margin:2rem;font-family:system-ui}pre{overflow:auto;line-height:1.6}span:target{background:#fff0ad}</style>"
                f"<h1>{html.escape(relative)}</h1><pre><code>{lines}</code></pre></html>"
            ).encode()
        new = Path(os.path.relpath(destination, Path(name).parent)).as_posix()
        return "](" + new + ("#" + fragment if fragment else "") + ")"

    pieces = re.split(r"(^```.*?^```[^\n]*)", content, flags=re.MULTILINE | re.DOTALL)
    return "".join(piece if index % 2 else re.sub(r"\]\(([^)]+)\)", replace, piece) for index, piece in enumerate(pieces))


def prepare(root=ROOT):
    pages, outputs = contents(root), {}
    for name, content in pages.items():
        outputs[name] = rewrite_links(content, name, pages, outputs, root).encode("utf-8")
    for path in (root / "docs/assets").glob("*"):
        if path.is_file():
            outputs[path.relative_to(root).as_posix()] = path.read_bytes()
    stage = root / ".opendoc/docs-source"
    if stage.resolve() != root.resolve() / ".opendoc/docs-source":
        raise ValueError("Unexpected documentation staging path")
    for path in stage.rglob("*"):
        if path.is_file() and path.relative_to(stage).as_posix() not in outputs:
            path.unlink()
    for name, data in outputs.items():
        path = stage / name
        path.parent.mkdir(parents=True, exist_ok=True)
        if not path.exists() or path.read_bytes() != data:
            path.write_bytes(data)


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("command", choices=["generate", "check", "build", "serve"])
    parser.add_argument("--address", default="127.0.0.1:8003")
    args = parser.parse_args(argv)
    try:
        if args.command == "generate":
            sync()
            return 0
        if args.command != "serve":
            sync(check=True)
        prepare()
        if args.command == "check":
            for example in sorted((ROOT / "examples").glob("*.py")):
                subprocess.run([sys.executable, str(example)], check=True, cwd=ROOT)
        command = ["serve", "--dev-addr", args.address] if args.command == "serve" else ["build", "--strict"]
        return subprocess.call([sys.executable, "-m", "mkdocs", *command], cwd=ROOT)
    except ValueError as error:
        print(error, file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
